<script src="{{ asset('template/lib/jquery/jquery.js') }}"></script>
<script src="{{ asset('template/lib/popper.js/popper.js') }}"></script>
<script src="{{ asset('template/lib/bootstrap/bootstrap.js') }}"></script>
<script src="{{ asset('template/lib/jquery-ui/jquery-ui.js') }}"></script>
<script src="{{ asset('template/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js') }}"></script>
<script src="{{ asset('template/lib/jquery.sparkline.bower/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('template/lib/d3/d3.js') }}"></script>
<script src="{{ asset('template/lib/rickshaw/rickshaw.min.js') }}"></script>
<script src="{{ asset('template/lib/chart.js/Chart.js') }}"></script>
<script src="{{ asset('template/lib/Flot/jquery.flot.js') }}"></script>
<script src="{{ asset('template/lib/Flot/jquery.flot.pie.js') }}"></script>
<script src="{{ asset('template/lib/Flot/jquery.flot.resize.js') }}"></script>
<script src="{{ asset('template/lib/flot-spline/jquery.flot.spline.js') }}"></script>

<script src="{{ asset('template/js/starlight.js') }}"></script>
<script src="{{ asset('template/js/ResizeSensor.js') }}"></script>
<script src="{{ asset('template/js/dashboard.js') }}"></script>
{{-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> --}}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
